spring:
  application:
    name: EventScheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/eventscheduler
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver